# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget opentelemetry-cpp::proto opentelemetry-cpp::api opentelemetry-cpp::sdk opentelemetry-cpp::common opentelemetry-cpp::trace opentelemetry-cpp::metrics opentelemetry-cpp::logs opentelemetry-cpp::version opentelemetry-cpp::resources opentelemetry-cpp::ext opentelemetry-cpp::http_client_curl opentelemetry-cpp::otlp_recordable opentelemetry-cpp::otlp_http_client opentelemetry-cpp::otlp_http_exporter opentelemetry-cpp::otlp_http_log_record_exporter opentelemetry-cpp::otlp_http_metric_exporter opentelemetry-cpp::ostream_span_exporter opentelemetry-cpp::ostream_metrics_exporter opentelemetry-cpp::ostream_log_record_exporter opentelemetry-cpp::in_memory_span_exporter opentelemetry-cpp::in_memory_metric_exporter)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target opentelemetry-cpp::proto
add_library(opentelemetry-cpp::proto SHARED IMPORTED)

set_target_properties(opentelemetry-cpp::proto PROPERTIES
  INTERFACE_LINK_LIBRARIES "protobuf::libprotobuf"
)

# Create imported target opentelemetry-cpp::api
add_library(opentelemetry-cpp::api INTERFACE IMPORTED)

set_target_properties(opentelemetry-cpp::api PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OPENTELEMETRY_ABI_VERSION_NO=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target opentelemetry-cpp::sdk
add_library(opentelemetry-cpp::sdk INTERFACE IMPORTED)

set_target_properties(opentelemetry-cpp::sdk PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target opentelemetry-cpp::common
add_library(opentelemetry-cpp::common STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::common PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::api;opentelemetry-cpp::sdk;Threads::Threads"
)

# Create imported target opentelemetry-cpp::trace
add_library(opentelemetry-cpp::trace STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::trace PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::common;opentelemetry-cpp::resources"
)

# Create imported target opentelemetry-cpp::metrics
add_library(opentelemetry-cpp::metrics STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::metrics PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::common;opentelemetry-cpp::resources"
)

# Create imported target opentelemetry-cpp::logs
add_library(opentelemetry-cpp::logs STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::logs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::resources;opentelemetry-cpp::common"
)

# Create imported target opentelemetry-cpp::version
add_library(opentelemetry-cpp::version STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::version PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::api;opentelemetry-cpp::sdk"
)

# Create imported target opentelemetry-cpp::resources
add_library(opentelemetry-cpp::resources STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::resources PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::common"
)

# Create imported target opentelemetry-cpp::ext
add_library(opentelemetry-cpp::ext INTERFACE IMPORTED)

set_target_properties(opentelemetry-cpp::ext PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::api"
)

# Create imported target opentelemetry-cpp::http_client_curl
add_library(opentelemetry-cpp::http_client_curl STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::http_client_curl PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::common;opentelemetry-cpp::ext;\$<LINK_ONLY:CURL::libcurl>"
)

# Create imported target opentelemetry-cpp::otlp_recordable
add_library(opentelemetry-cpp::otlp_recordable STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::otlp_recordable PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::logs;opentelemetry-cpp::metrics;opentelemetry-cpp::trace;opentelemetry-cpp::resources;opentelemetry-cpp::proto"
)

# Create imported target opentelemetry-cpp::otlp_http_client
add_library(opentelemetry-cpp::otlp_http_client STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::otlp_http_client PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::sdk;opentelemetry-cpp::ext;\$<LINK_ONLY:opentelemetry-cpp::proto>;\$<LINK_ONLY:opentelemetry-cpp::http_client_curl>;\$<LINK_ONLY:nlohmann_json::nlohmann_json>"
)

# Create imported target opentelemetry-cpp::otlp_http_exporter
add_library(opentelemetry-cpp::otlp_http_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::otlp_http_exporter PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::otlp_recordable;opentelemetry-cpp::otlp_http_client"
)

# Create imported target opentelemetry-cpp::otlp_http_log_record_exporter
add_library(opentelemetry-cpp::otlp_http_log_record_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::otlp_http_log_record_exporter PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::otlp_recordable;opentelemetry-cpp::otlp_http_client"
)

# Create imported target opentelemetry-cpp::otlp_http_metric_exporter
add_library(opentelemetry-cpp::otlp_http_metric_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::otlp_http_metric_exporter PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::otlp_recordable;opentelemetry-cpp::otlp_http_client"
)

# Create imported target opentelemetry-cpp::ostream_span_exporter
add_library(opentelemetry-cpp::ostream_span_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::ostream_span_exporter PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::trace"
)

# Create imported target opentelemetry-cpp::ostream_metrics_exporter
add_library(opentelemetry-cpp::ostream_metrics_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::ostream_metrics_exporter PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::metrics"
)

# Create imported target opentelemetry-cpp::ostream_log_record_exporter
add_library(opentelemetry-cpp::ostream_log_record_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::ostream_log_record_exporter PROPERTIES
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::logs"
)

# Create imported target opentelemetry-cpp::in_memory_span_exporter
add_library(opentelemetry-cpp::in_memory_span_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::in_memory_span_exporter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::trace"
)

# Create imported target opentelemetry-cpp::in_memory_metric_exporter
add_library(opentelemetry-cpp::in_memory_metric_exporter STATIC IMPORTED)

set_target_properties(opentelemetry-cpp::in_memory_metric_exporter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "opentelemetry-cpp::metrics"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/opentelemetry-cpp-target-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
